// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { useAntdConfig, useAntdConfigSetter } from '/Users/yanjinqiang/WebstormProjects/management/src/.umi/plugin-antd';
export { KeepAlive, useActivate, useUnactivate, withActivation, withAliveScope, useAliveController, autoFixContext } from '/Users/yanjinqiang/WebstormProjects/management/src/.umi/plugin-keepAlive';
// plugins types.d.ts
export * from '/Users/yanjinqiang/WebstormProjects/management/src/.umi/plugin-antd/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/yanjinqiang/WebstormProjects/management/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/Users/yanjinqiang/WebstormProjects/management/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/yanjinqiang/WebstormProjects/management/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
